# Generated by Django 4.0.1 on 2022-02-24 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_alter_account_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayWayMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.URLField(verbose_name='backend endpoint')),
                ('success', models.URLField(verbose_name='success url')),
                ('fail', models.URLField(verbose_name='fail url')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='owner account')),
            ],
            options={
                'verbose_name': 'pay way meta data',
                'verbose_name_plural': 'pay way meta data',
                'db_table': 'payway_metadata',
            },
        ),
        migrations.CreateModel(
            name='PayWayKeys',
            fields=[
                ('public', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='publishable key')),
                ('private', models.CharField(max_length=64, verbose_name='secret key')),
                ('meta_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payway.paywaymetadata')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='key_pair', to=settings.AUTH_USER_MODEL, verbose_name='key pair owner')),
            ],
            options={
                'verbose_name': 'pay way key',
                'verbose_name_plural': 'pay way keys',
                'db_table': 'payway_keys',
            },
        ),
    ]
