# Generated by Django 4.0.1 on 2022-02-24 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayWayKeys',
            fields=[
                ('public', models.CharField(editable=False, max_length=64, primary_key=True, serialize=False, verbose_name='publishable key')),
                ('private', models.CharField(max_length=64, verbose_name='secret key')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_pairs', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='key pair owner')),
            ],
            options={
                'verbose_name': 'pay way key',
                'verbose_name_plural': 'pay way keys',
                'db_table': 'payway_keys',
            },
        ),
    ]
