# Generated by Django 4.0.1 on 2022-03-01 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paywaykeys',
            name='meta_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payway.paywaymetadata'),
        ),
    ]
