# Generated by Django 4.0.1 on 2022-03-01 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payway', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paywaymetadata',
            name='date_created',
            field=models.DateField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paywaymetadata',
            name='app_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='app name'),
        ),
    ]
