# Generated by Django 4.0.1 on 2022-03-02 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payway", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paywaykeys",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="key_pairs",
                to=settings.AUTH_USER_MODEL,
                verbose_name="key pair owner",
            ),
        ),
    ]
