# Generated by Django 4.0.1 on 2022-03-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
        ("payway", "0003_alter_paywaykeys_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="paywaymetadata",
            name="transactions",
            field=models.ManyToManyField(to="transaction.Transaction"),
        ),
    ]
