# Generated by Django 4.0.1 on 2022-01-19 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document_id',
            field=models.CharField(default='v26838989', max_length=15, validators=[django.core.validators.RegexValidator(message='your document id is not well formatted', regex='^[eEvVjJ]\\d+$')], verbose_name='document id (cedula/rif)'),
            preserve_default=False,
        ),
    ]
