# Generated by Django 4.0.1 on 2022-03-03 10:06

from django.db import migrations

def generate_devices(apps, schema_editor):
    User = apps.get_model("user", "User")
    EmailDevice = apps.get_model("otp_email", "EmailDevice")
    for user in User.objects.all():
        EmailDevice.objects.create(user=user, name=f"personal device for user {user.pk}", confirmed=True)


class Migration(migrations.Migration):

    dependencies = [
        ('otp_email', '0004_throttling'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDevice',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('otp_email.emaildevice',),
        ),
        migrations.RunPython(generate_devices),
    ]
