# Generated by Django 4.0.1 on 2022-03-17 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_emaildevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('NATURAL', 'Natural'), ('JURIDIC', 'Juridic')], max_length=50, verbose_name='user type'),
        ),
    ]
