# Generated by Django 4.0.1 on 2022-02-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='status',
        ),
    ]
