# Generated by Django 4.0.1 on 2022-02-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='ammount of money')),
                ('reason', models.CharField(max_length=50, verbose_name='reason why the transaction is being carried out')),
                ('date', models.DateField(auto_now=True, verbose_name='transaction date')),
                ('target_account', models.CharField(max_length=20, verbose_name='target account')),
                ('source_account', models.CharField(max_length=20, verbose_name='source account')),
            ],
        ),
    ]
