# Generated by Django 4.0.1 on 2022-03-29 11:14

import degvabank.apps.transaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[degvabank.apps.transaction.models.validate_positive], verbose_name='amount of money'),
        ),
    ]
