# Generated by Django 4.0.1 on 2022-02-03 07:47

import creditcards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('security_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
                ('expiration_date', creditcards.models.CardExpiryField(verbose_name='expiration date')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cards', to='account.account', verbose_name='account')),
            ],
            options={
                'verbose_name': 'debit card',
                'verbose_name_plural': 'debit cards',
                'db_table': 'debit_cards',
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', creditcards.models.CardNumberField(max_length=25, verbose_name='card number')),
                ('security_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='security code')),
                ('expiration_date', creditcards.models.CardExpiryField(verbose_name='expiration date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit_cards', to=settings.AUTH_USER_MODEL, verbose_name='card owner')),
            ],
            options={
                'verbose_name': 'credit card',
                'verbose_name_plural': 'credit cards',
                'db_table': 'credit_cards',
            },
        ),
    ]
