# Generated by Django 4.0.1 on 2022-02-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='card should be used by owner?', verbose_name='card is active'),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='card should be used by owner?', verbose_name='card is active'),
        ),
    ]
