# Generated by Django 4.0.1 on 2022-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='date_processed',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='date processed'),
        ),
    ]
